name: Build and Deploy

on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.USER }}
          POSTGRES_PASSWORD: ${{ secrets.SENHA }}
          POSTGRES_DB: database
        ports:
          - 5432:5432

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.4"

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r ./BACKEND/requirements.txt

      - name: Esperar PostgreSQL iniciar
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 && echo "PostgreSQL pronto!" && exit 0
            echo "Aguardando PostgreSQL..."
            sleep 2
          done
          echo "O PostgreSQL não iniciou a tempo." && exit 1

      - name: Depurar DATABASE_URL
        run: |
          echo "DATABASE_URL=${DATABASE_URL//:${{ secrets.SENHA }}/:*****}"
        env:
          DATABASE_URL: "postgresql://${{ secrets.USER }}:${{ secrets.SENHA }}@localhost:5432/database"

      - name: Testar conexão com PostgreSQL
        run: |
          PGPASSWORD=${{ secrets.SENHA }} psql -h localhost -U ${{ secrets.USER }} -d database -c "\dt"

      - name: Executar pytest
        env:
          DATABASE_URL: "postgresql://${{ secrets.USER }}:${{ secrets.SENHA }}@localhost:5432/database"
        run: pytest ./BACKEND/teste.py
