name: Build and Deploy

on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.USER}}
          POSTGRES_PASSWORD: ${{ secrets.SENHA}}
          POSTGRES_DB: database
        ports:
          - 5432:5432
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: instalando o python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.4"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: instalar dependencias
        run: pip install -r ./BACKEND/requirements.txt
      - name: Esperando o PostgreSQL ficar pronto
        run: sleep 15
      - name: Executar pytest
        env:
          DATABASE_URL: "postgresql://${{ secrets.USER }}:${{ secrets.SENHA }}@localhost:5432/database"
        run: pytest ./BACKEND/teste.py
